version: "3.9"

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - db
      - redis
    networks:
      - appnet

  web:
    image: nginx:1.27-alpine
    container_name: laravel_web
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - appnet

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_0900_ai_ci",
      "--default-authentication-plugin=mysql_native_password"
    ]
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - appnet

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - appnet

  node:
    build:
      context: ./docker/node
    container_name: nextjs_frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8080
      - TZ=Asia/Tokyo
    depends_on:
      - web
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:
    driver: bridge
